packages:
  - "api"
  - "web"
  - "mobile"
  - "desktop"
  - "packages/*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "bcrypt"
  - "sharp"
  - "prisma"
  - "msgpackr-extract"
